BEGIN;
DROP TABLE IF EXISTS team_intelligence CASCADE;
CREATE TABLE team_intelligence (
    id SERIAL PRIMARY KEY,
    team_name VARCHAR(255) NOT NULL,
    team_name_normalized VARCHAR(255),
    team_statistics_id INTEGER,
    api_football_id INTEGER,
    country VARCHAR(100),
    league VARCHAR(255),
    league_id INTEGER,
    league_tier INTEGER DEFAULT 2,
    season VARCHAR(20) DEFAULT '2024-2025',
    current_style VARCHAR(50),
    current_style_score INTEGER DEFAULT 50,
    current_pressing VARCHAR(20) DEFAULT 'medium',
    current_form VARCHAR(20) DEFAULT 'neutral',
    current_form_points INTEGER,
    season_style VARCHAR(50),
    season_style_score INTEGER DEFAULT 50,
    style_trend VARCHAR(20) DEFAULT 'stable',
    style_trend_strength INTEGER DEFAULT 0,
    style_last_changed_at TIMESTAMP,
    style_change_reason VARCHAR(255),
    home_strength INTEGER DEFAULT 50,
    home_win_rate NUMERIC(5,2),
    home_draw_rate NUMERIC(5,2),
    home_loss_rate NUMERIC(5,2),
    home_goals_scored_avg NUMERIC(4,2),
    home_goals_conceded_avg NUMERIC(4,2),
    home_btts_rate NUMERIC(5,2),
    home_over25_rate NUMERIC(5,2),
    home_over15_rate NUMERIC(5,2),
    home_clean_sheet_rate NUMERIC(5,2),
    home_failed_to_score_rate NUMERIC(5,2),
    home_profile VARCHAR(50),
    away_strength INTEGER DEFAULT 50,
    away_win_rate NUMERIC(5,2),
    away_draw_rate NUMERIC(5,2),
    away_loss_rate NUMERIC(5,2),
    away_goals_scored_avg NUMERIC(4,2),
    away_goals_conceded_avg NUMERIC(4,2),
    away_btts_rate NUMERIC(5,2),
    away_over25_rate NUMERIC(5,2),
    away_over15_rate NUMERIC(5,2),
    away_clean_sheet_rate NUMERIC(5,2),
    away_failed_to_score_rate NUMERIC(5,2),
    away_profile VARCHAR(50),
    draw_tendency INTEGER DEFAULT 50,
    goals_tendency INTEGER DEFAULT 50,
    btts_tendency INTEGER DEFAULT 50,
    clean_sheet_tendency INTEGER DEFAULT 50,
    xg_for_avg NUMERIC(4,2),
    xg_against_avg NUMERIC(4,2),
    xg_difference NUMERIC(4,2),
    overperformance_goals NUMERIC(4,2),
    first_half_goals_pct NUMERIC(5,2),
    second_half_goals_pct NUMERIC(5,2),
    late_goals_pct NUMERIC(5,2),
    conceded_late_pct NUMERIC(5,2),
    first_scorer_rate NUMERIC(5,2),
    comeback_rate NUMERIC(5,2),
    vs_top_teams JSONB DEFAULT '{}',
    vs_bottom_teams JSONB DEFAULT '{}',
    after_europe JSONB DEFAULT '{}',
    congested_schedule JSONB DEFAULT '{}',
    tags JSONB DEFAULT '[]',
    market_alerts JSONB DEFAULT '{}',
    current_coach VARCHAR(255),
    coach_style VARCHAR(50),
    coach_tenure_months INTEGER,
    coach_win_rate NUMERIC(5,2),
    coach_draw_rate NUMERIC(5,2),
    coach_avg_goals NUMERIC(4,2),
    data_quality_score INTEGER DEFAULT 50,
    confidence_overall INTEGER DEFAULT 50,
    confidence_breakdown JSONB DEFAULT '{}',
    matches_analyzed INTEGER DEFAULT 0,
    is_reliable BOOLEAN DEFAULT false,
    data_sources JSONB DEFAULT '[]',
    raw_computation_log JSONB DEFAULT '{}',
    last_api_sync TIMESTAMP,
    last_computed_at TIMESTAMP,
    computation_version VARCHAR(20) DEFAULT '1.0',
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    CONSTRAINT uq_team_intelligence_name UNIQUE(team_name)
);
CREATE INDEX idx_ti_team_name ON team_intelligence(team_name);
CREATE INDEX idx_ti_league ON team_intelligence(league);
CREATE INDEX idx_ti_country ON team_intelligence(country);
CREATE INDEX idx_ti_tags ON team_intelligence USING GIN(tags);
CREATE INDEX idx_ti_market_alerts ON team_intelligence USING GIN(market_alerts);
CREATE INDEX idx_ti_current_style ON team_intelligence(current_style);
CREATE INDEX idx_ti_draw_tendency ON team_intelligence(draw_tendency);
COMMIT;
